---
title: "Introduction to the trophicR Package"
author: "Virgile Baudrot"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to the trophicR Package}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

This vignette is a tutorial to help the use of the trophicR package.
trophicR is dedicated to the Bayesian estimate of functional resonse with one
or several prey species.

# A first simple example

```{r H2testData}
 data("data_H2test")
```

```{r H2testFit}
fit_H2test <- trophicFit_H2test(data = data_H2test)
```

# Fox predation on voles

```{r foxData}
data("fox_Raoul2010")
```

## Holling type 2

```{r foxFitH2}
fit_foxH2 <- trophicFit(data = fox_Raoul2010, trophic_model = "holling2")
```

```{r foxResultH2}
# pairs(fit_H2, pars = c("a", "h", "lp__"), log = TRUE, las = 1)
```

## Holling type 3

```{r foxFitH3}
fit_foxH3 <- trophicFit(data = fox_Raoul2010, trophic_model = "holling3")
```

```{r foxResultH3}
# pairs(fit_H2, pars = c("a", "h", "lp__"), log = TRUE, las = 1)
```
